"""Add index in invoice status and update customer

Revision ID: 057d91536fff
Revises: 675e88a73a3f
Create Date: 2025-01-19 12:41:21.669860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '057d91536fff'
down_revision: Union[str, None] = '675e88a73a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'customer_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.alter_column('customers', 'customer_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
