"""user_org_id to string for clerk

Revision ID: 064514f2e708
Revises: 62b9984ef317
Create Date: 2025-04-24 13:59:00.894543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064514f2e708'
down_revision: Union[str, None] = '62b9984ef317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('customers', 'org_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('invoices', 'org_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('payments', 'org_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('scheduled_downgrades', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('scheduled_downgrades', 'org_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'org_id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'org_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('scheduled_downgrades', 'org_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('scheduled_downgrades', 'user_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('payments', 'org_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('payments', 'user_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('invoices', 'org_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('invoices', 'user_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('customers', 'org_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('customers', 'user_id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
