"""updated invoice model - paddle

Revision ID: 0b9e4ba9487d
Revises: a941bd91ce82
Create Date: 2025-04-11 13:26:50.029479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b9e4ba9487d'
down_revision: Union[str, None] = 'a941bd91ce82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('transaction_id', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('psp_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'psp_name')
    op.drop_column('invoices', 'transaction_id')
    # ### end Alembic commands ###
