"""updated plan model -paddle

Revision ID: 16ec21d1fb00
Revises: f56c5f707c39
Create Date: 2025-04-10 13:31:15.820225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ec21d1fb00'
down_revision: Union[str, None] = 'f56c5f707c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('psp_plan_id', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('psp_price_id', sa.String(), nullable=True))
    op.add_column('plans', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_plans_razorpay_plan_id', table_name='plans')
    op.create_index('ix_plans_psp_plan_id', 'plans', ['psp_plan_id'], unique=True)
    op.drop_column('plans', 'razorpay_plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('razorpay_plan_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('ix_plans_psp_plan_id', table_name='plans')
    op.create_index('ix_plans_razorpay_plan_id', 'plans', ['razorpay_plan_id'], unique=False)
    op.drop_column('plans', 'is_active')
    op.drop_column('plans', 'psp_price_id')
    op.drop_column('plans', 'psp_plan_id')
    # ### end Alembic commands ###
