"""Add necessary indexes and separate invoice

Revision ID: 2e89048388dc
Revises: c7cf19d5a1b9
Create Date: 2025-01-19 11:17:40.905891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e89048388dc'
down_revision: Union[str, None] = 'c7cf19d5a1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('org_id', sa.Integer(), nullable=False))

    # Create the new enum type for psp_name
    psp_enum = sa.Enum('STRIPE', 'RAZORPAY', name='pspname')
    psp_enum.create(op.get_bind(), checkfirst=True)

    # Alter the psp_name column with explicit casting
    op.execute("ALTER TABLE customers ALTER COLUMN psp_name TYPE pspname USING psp_name::TEXT::pspname")

    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=False)
    op.create_index('ix_customers_user_org', 'customers', ['user_id', 'org_id'], unique=False)

    # Alter the invoice_date column with explicit casting
    op.execute(
        "ALTER TABLE invoices ALTER COLUMN invoice_date TYPE TIMESTAMP WITH TIME ZONE USING invoice_date::TIMESTAMP WITH TIME ZONE"
    )
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')

    # Revert the invoice_date column type
    op.execute(
        "ALTER TABLE invoices ALTER COLUMN invoice_date TYPE VARCHAR USING invoice_date::TEXT"
    )

    op.drop_index('ix_customers_user_org', table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')

    # Revert the enum type for psp_name
    op.execute("ALTER TABLE customers ALTER COLUMN psp_name TYPE VARCHAR USING psp_name::TEXT")
    psp_enum = sa.Enum('STRIPE', 'RAZORPAY', name='pspname')
    psp_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_column('customers', 'org_id')
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
