"""Change in plan schema for basic plan

Revision ID: 446213422fdc
Revises: 80e7996ca542
Create Date: 2025-01-28 12:09:34.067346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446213422fdc'
down_revision: Union[str, None] = '80e7996ca542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'razorpay_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'razorpay_plan_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
