"""Add status in subscriptions

Revision ID: 5748c0ce3ed4
Revises: a25abc5e18c5
Create Date: 2025-01-11 22:50:42.213666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5748c0ce3ed4'
down_revision: Union[str, None] = 'a25abc5e18c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'status')
    # ### end Alembic commands ###
