"""let invoice due date nullable

Revision ID: 5cdae26dce95
Revises: cd047173404b
Create Date: 2025-01-29 19:09:51.837173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cdae26dce95'
down_revision: Union[str, None] = 'cd047173404b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'next_due_date',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'next_due_date',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
