"""removed unique psp plan id

Revision ID: 62b9984ef317
Revises: d9855a6aab86
Create Date: 2025-04-22 18:20:50.395049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b9984ef317'
down_revision: Union[str, None] = 'd9855a6aab86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plans_psp_plan_id', table_name='plans')
    op.drop_index('ix_plans_psp_price_id', table_name='plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_plans_psp_price_id', 'plans', ['psp_price_id'], unique=False)
    op.create_index('ix_plans_psp_plan_id', 'plans', ['psp_plan_id'], unique=False)
    # ### end Alembic commands ###
