"""Add psp invoice id to invoices table

Revision ID: 675e88a73a3f
Revises: 2e89048388dc
Create Date: 2025-01-19 11:49:28.011110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675e88a73a3f'
down_revision: Union[str, None] = '2e89048388dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('psp_invoice_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_invoices_psp_invoice_id'), 'invoices', ['psp_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_psp_invoice_id'), table_name='invoices')
    op.drop_column('invoices', 'psp_invoice_id')
    # ### end Alembic commands ###
