"""Make plan id nullable in coupons

Revision ID: 8fcf6aead411
Revises: 5748c0ce3ed4
Create Date: 2025-01-15 22:11:44.124246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcf6aead411'
down_revision: Union[str, None] = '5748c0ce3ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_coupons', 'plan_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('plan_coupons_plan_id_fkey', 'plan_coupons', type_='foreignkey')
    op.drop_column('plan_coupons', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_coupons', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key('plan_coupons_plan_id_fkey', 'plan_coupons', 'plans', ['plan_id'], ['id'])
    op.alter_column('plan_coupons', 'plan_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
