"""Add next due date in invoice

Revision ID: a05a5d9671dc
Revises: a09ca36e041d
Create Date: 2025-01-20 17:21:16.012074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05a5d9671dc'
down_revision: Union[str, None] = 'a09ca36e041d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'next_due_date')
    # ### end Alembic commands ###
