"""Add user and org id in payments

Revision ID: a09ca36e041d
Revises: 057d91536fff
Create Date: 2025-01-20 16:33:46.847774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09ca36e041d'
down_revision: Union[str, None] = '057d91536fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('org_id', sa.Integer(), nullable=False))
    op.create_index('ix_payments_user_org', 'payments', ['user_id', 'org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_user_org', table_name='payments')
    op.drop_column('payments', 'org_id')
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
