"""Add user and org and indexes in invoices

Revision ID: a6de6e7a6e35
Revises: a05a5d9671dc
Create Date: 2025-01-20 18:33:12.966034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6de6e7a6e35'
down_revision: Union[str, None] = 'a05a5d9671dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('org_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_index('ix_invoices_user_org', 'invoices', ['user_id', 'org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invoices_user_org', table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_column('invoices', 'org_id')
    op.drop_column('invoices', 'user_id')
    # ### end Alembic commands ###
