"""updated psp enum -paddle

Revision ID: a941bd91ce82
Revises: 16ec21d1fb00
Create Date: 2025-04-10 16:53:45.920656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a941bd91ce82'
down_revision: Union[str, None] = '16ec21d1fb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_plans_psp_price_id', 'plans', ['psp_price_id'], unique=True)
    op.execute("ALTER TYPE pspname ADD VALUE 'PADDLE'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_plans_psp_price_id', table_name='plans')
    # ### end Alembic commands ###
