"""change name to psp_subscription_id

Revision ID: c6f8fe8fbdbf
Revises: ad254ac81fe9
Create Date: 2025-01-24 13:01:12.427532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f8fe8fbdbf'
down_revision: Union[str, None] = 'ad254ac81fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('psp_subscription_id', sa.String(length=255), nullable=True))

    # Migrate data from razorpay_subscription_id to psp_subscription_id
    op.execute(
        "UPDATE subscriptions SET psp_subscription_id = razorpay_subscription_id"
    )

    op.drop_index('ix_subscriptions_razorpay_subscription_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_psp_subscription_id'), 'subscriptions', ['psp_subscription_id'], unique=False)
    op.drop_column('subscriptions', 'razorpay_subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('razorpay_subscription_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # Migrate data back from psp_subscription_id to razorpay_subscription_id
    op.execute(
        "UPDATE subscriptions SET razorpay_subscription_id = psp_subscription_id"
    )

    op.drop_index(op.f('ix_subscriptions_psp_subscription_id'), table_name='subscriptions')
    op.create_index('ix_subscriptions_razorpay_subscription_id', 'subscriptions', ['razorpay_subscription_id'], unique=False)
    op.drop_column('subscriptions', 'psp_subscription_id')
    # ### end Alembic commands ###

