"""orgid nullable true

Revision ID: d9855a6aab86
Revises: da4e3fec413e
Create Date: 2025-04-18 14:54:10.360218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9855a6aab86'
down_revision: Union[str, None] = 'da4e3fec413e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('invoices', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('payments', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('scheduled_downgrades', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('scheduled_downgrades', 'org_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('invoices', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('customers', 'org_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
