"""nullable psp_invoice_id - paddle

Revision ID: da4e3fec413e
Revises: 0b9e4ba9487d
Create Date: 2025-04-11 15:51:17.334196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4e3fec413e'
down_revision: Union[str, None] = '0b9e4ba9487d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'psp_invoice_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'psp_invoice_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
