"""Add short url in invoices

Revision ID: e6585dc01222
Revises: a6de6e7a6e35
Create Date: 2025-01-21 18:08:52.371620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6585dc01222'
down_revision: Union[str, None] = 'a6de6e7a6e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('short_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'short_url')
    # ### end Alembic commands ###
