"""Add scheduled downgrade for 14 day trial

Revision ID: f56c5f707c39
Revises: ae742f5e77de
Create Date: 2025-02-17 10:53:40.652940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56c5f707c39'
down_revision: Union[str, None] = 'ae742f5e77de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_downgrades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_downgrades_status'), 'scheduled_downgrades', ['status'], unique=False)
    op.create_index('ix_scheduleddowngrade_user_org', 'scheduled_downgrades', ['user_id', 'org_id'], unique=False)
    op.add_column('subscriptions', sa.Column('is_trial', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_subscriptions_is_trial'), 'subscriptions', ['is_trial'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_is_trial'), table_name='subscriptions')
    op.drop_column('subscriptions', 'is_trial')
    op.drop_index('ix_scheduleddowngrade_user_org', table_name='scheduled_downgrades')
    op.drop_index(op.f('ix_scheduled_downgrades_status'), table_name='scheduled_downgrades')
    op.drop_table('scheduled_downgrades')
    # ### end Alembic commands ###
